version: 2.1

orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@3.0.1

jobs:
  initialize:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Initialize
          command: |
            echo "🚀 Starting pipeline"
            echo "Branch: $CIRCLE_BRANCH"
            echo "Commit: $CIRCLE_SHA1"

  install-dependencies:
    docker:
      - image: cimg/node:20.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci

  test:
    docker:
      - image: cimg/node:20.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run tests
          command: npm test

  docker_build_and_push:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker login
          command: echo ${DOCKER_REGISTRY_PASSWORD} | docker login -u ${DOCKER_REGISTRY_USERNAME} --password-stdin
      - run:
          name: Set Image Tag
          command: |
            SHORT_SHA=$(echo "${CIRCLE_SHA1}" | cut -c1-7)
            echo "export IMAGE_TAG=${SHORT_SHA}" > .env
      - run:
          name: Docker build
          command: docker build -t ${DOCKER_REGISTRY_USERNAME}/joke-jolt:${SHORT_SHA} .
      - run:
          name: Docker push
          command: docker push ${DOCKER_REGISTRY_USERNAME}/joke-jolt:${SHORT_SHA}

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - initialize
      - install-dependencies:
          requires:
            - initialize
      - test:
          requires:
            - install-dependencies
      - docker_build_and_push:
          requires:
            - test
          filters:
            branches:
              only:
                - main
